version: "3"
services:
 mysql:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    MYSQL_USER: "${MYSQL_USER}"
    MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  volumes:
   - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
   - ./etc/mysql:/etc/mysql
   - ./var/lib/mysql:/var/lib/mysql
   - ./var/run/mysqld:/var/run/mysqld
  ports:
   - "3306:3306"
 referential:
  image: numercity-referential:latest
  ports:
   - "8080:8080"
