version: "3"
services:
 mysql:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    MYSQL_USER: "${MYSQL_USER}"
    MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  volumes:
   - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
   - ./etc/mysql:/etc/mysql
   - ./var/lib/mysql:/var/lib/mysql
   - ./var/logs:/var/logs
   - ./var/run/mysqld:/var/run/mysqld
   - /usr/share/zoneinfo:/usr/share/zoneinfo
  ports:
   - "3306:3306"
  security_opt:
   - seccomp:unconfined
 referential:
  image: numercity-referential:latest
  volumes:
   - ./var/logs:/logs
  ports:
   - "8080:8080"
  depends_on:
   - "auth"
   - "mysql"
 request:
  image: numercity-request:latest
  volumes:
   - ./var/logs:/logs
  ports:
   - "8081:8081"
  depends_on:
   - "auth"
   - "referential"
   - "admin"
   - "user"
   - "vote"
   - "mysql"
 user:
  image: numercity-user:latest
  volumes:
   - ./var/logs:/logs
   - ./var/numercity/proof:/proof
  ports:
   - "8082:8082"
  depends_on:
   - "auth"
   - "referential"
   - "admin"
   - "mysql"
 auth:
  image: numercity-auth:latest
  volumes:
   - ./var/logs:/logs
   - ./var/numercity/KeyPair:/opt/numercity/KeyPair
  ports:
   - "8083:8083"
  depends_on:
   - "mysql"
 view:
  image: numercity-view:latest
  volumes:
   - ./var/logs:/logs
  ports:
   - "8084:8084"
  depends_on:
   - "auth"
   - "referential"
   - "admin"
   - "user"
   - "vote"
   - "request"
   - "mysql"
 vote:
  image: numercity-vote:latest
  volumes:
   - ./var/logs:/logs
  ports:
   - "8085:8085"
  depends_on:
   - "auth"
   - "referential"
   - "admin"
   - "user"
   - "mysql"
 admin:
  image: numercity-admin:latest
  volumes:
   - ./var/logs:/logs
  ports:
   - "8087:8087"
  depends_on:
   - "auth"
   - "referential"
   - "mysql"
 numercity.dev:
  image: nginx
  volumes:
   - ./etc/nginx:/etc/nginx
   - ./usr/share/nginx:/usr/share/nginx
   - ./var/www/numercity.dev/certs:/var/www/numercity.dev/certs
   - ./var/www/numercity.dev/html:/var/www/numercity.dev/html
  ports:
   - "80:80"
   - "443:443"
  depends_on:
   - "auth"
   - "referential"
   - "admin"
   - "user"
   - "vote"
   - "request"
   - "view"
